accepted = [
    "0BSD",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "BSL-1.0",
    "CC0-1.0",
    "CDLA-Permissive-2.0",
    "ISC",
    "LicenseRef-Slint-Royalty-free-2.0",
    "MIT",
    "MPL-2.0",
    "NCSA",
    "Unicode-3.0",
    "Unicode-DFS-2016",
    "Unlicense",
    "Zlib",
]
targets = [
    "x86_64-unknown-linux-gnu",
    "x86_64-pc-windows-msvc",
]
ignore-build-dependencies = true
ignore-dev-dependencies = true
ignore-transitive-dependencies = false

[ring]
accepted = ["OpenSSL"]

[i-slint-backend-selector.clarify]
license = "LicenseRef-Slint-Royalty-free-2.0"

[[i-slint-backend-selector.clarify.files]]
path = "LICENSES/LicenseRef-Slint-Royalty-free-2.0.md"
checksum = "5167f5056e850419106ab6265efbdca7cba4d99c849d1445ca0bbf6a1e2315fe"

[i-slint-backend-winit.clarify]
license = "LicenseRef-Slint-Royalty-free-2.0"

[[i-slint-backend-winit.clarify.files]]
path = "LICENSES/LicenseRef-Slint-Royalty-free-2.0.md"
checksum = "5167f5056e850419106ab6265efbdca7cba4d99c849d1445ca0bbf6a1e2315fe"

[i-slint-common.clarify]
license = "LicenseRef-Slint-Royalty-free-2.0"

[[i-slint-common.clarify.files]]
path = "LICENSES/LicenseRef-Slint-Royalty-free-2.0.md"
checksum = "5167f5056e850419106ab6265efbdca7cba4d99c849d1445ca0bbf6a1e2315fe"

[i-slint-compiler.clarify]
license = "LicenseRef-Slint-Royalty-free-2.0"

[[i-slint-compiler.clarify.files]]
path = "LICENSES/LicenseRef-Slint-Royalty-free-2.0.md"
checksum = "5167f5056e850419106ab6265efbdca7cba4d99c849d1445ca0bbf6a1e2315fe"

[i-slint-core.clarify]
license = "LicenseRef-Slint-Royalty-free-2.0"

[[i-slint-core.clarify.files]]
path = "LICENSES/LicenseRef-Slint-Royalty-free-2.0.md"
checksum = "5167f5056e850419106ab6265efbdca7cba4d99c849d1445ca0bbf6a1e2315fe"

[i-slint-core-macros.clarify]
license = "LicenseRef-Slint-Royalty-free-2.0"

[[i-slint-core-macros.clarify.files]]
path = "LICENSES/LicenseRef-Slint-Royalty-free-2.0.md"
checksum = "5167f5056e850419106ab6265efbdca7cba4d99c849d1445ca0bbf6a1e2315fe"

[i-slint-renderer-femtovg.clarify]
license = "LicenseRef-Slint-Royalty-free-2.0"

[[i-slint-renderer-femtovg.clarify.files]]
path = "LICENSES/LicenseRef-Slint-Royalty-free-2.0.md"
checksum = "5167f5056e850419106ab6265efbdca7cba4d99c849d1445ca0bbf6a1e2315fe"

[i-slint-renderer-software.clarify]
license = "LicenseRef-Slint-Royalty-free-2.0"

[[i-slint-renderer-software.clarify.files]]
path = "LICENSES/LicenseRef-Slint-Royalty-free-2.0.md"
checksum = "5167f5056e850419106ab6265efbdca7cba4d99c849d1445ca0bbf6a1e2315fe"

[slint.clarify]
license = "LicenseRef-Slint-Royalty-free-2.0"

[[slint.clarify.files]]
path = "LICENSES/LicenseRef-Slint-Royalty-free-2.0.md"
checksum = "5167f5056e850419106ab6265efbdca7cba4d99c849d1445ca0bbf6a1e2315fe"

[slint-macros.clarify]
license = "LicenseRef-Slint-Royalty-free-2.0"

[[slint-macros.clarify.files]]
path = "LICENSES/LicenseRef-Slint-Royalty-free-2.0.md"
checksum = "5167f5056e850419106ab6265efbdca7cba4d99c849d1445ca0bbf6a1e2315fe"
