#[derive(Debug, Clone)]
pub enum Command {
    AutoSyncTick,
    CleanCache,
    ExportWallpaper { id: String },
    ImportImage,
    InstallLockScreenIntegration,
    LoadSnapshot,
    OpenDataFolder,
    OpenFavoritesFolder,
    OpenLogsFolder,
    OpenReleasePage,
    OpenWallpaperInfo { id: String },
    RevealCurrentImage,
    RevealWallpaper { id: String },
    RemoveWallpaper { id: String },
    Scan,
    SyncCurrent,
    SyncWallpaper { id: String },
    WarmThumbnails,
    SetAutoSync(bool),
    SetAutomaticUpdateChecks(bool),
    SetFavorite { id: String, favorite: bool },
    SetHistoryLimit(Option<u16>),
    SetKeepRunningInBackground(bool),
    SetLanguage(String),
    SetLockScreenBlurMode(String),
    SetLockScreenDisplayMode(String),
    SetLockScreenIntegrationEnabled(bool),
    SetWallpaperSource(String),
    SetStartAtLogin(bool),
    SetSyncInterval(u32),
    SetTheme(String),
}

impl Command {
    pub fn name(&self) -> &'static str {
        match self {
            Self::AutoSyncTick => "auto_sync_tick",
            Self::CleanCache => "clean_cache",
            Self::ExportWallpaper { .. } => "export_wallpaper",
            Self::ImportImage => "import_image",
            Self::InstallLockScreenIntegration => "install_lock_screen_integration",
            Self::LoadSnapshot => "load_snapshot",
            Self::OpenDataFolder => "open_data_folder",
            Self::OpenFavoritesFolder => "open_favorites_folder",
            Self::OpenLogsFolder => "open_logs_folder",
            Self::OpenReleasePage => "open_release_page",
            Self::OpenWallpaperInfo { .. } => "open_wallpaper_info",
            Self::RevealCurrentImage => "reveal_current_image",
            Self::RevealWallpaper { .. } => "reveal_wallpaper",
            Self::RemoveWallpaper { .. } => "remove_wallpaper",
            Self::Scan => "scan",
            Self::SyncCurrent => "sync_current",
            Self::SyncWallpaper { .. } => "sync_wallpaper",
            Self::WarmThumbnails => "warm_thumbnails",
            Self::SetAutoSync(_) => "set_auto_sync",
            Self::SetAutomaticUpdateChecks(_) => "set_automatic_update_checks",
            Self::SetFavorite { .. } => "set_favorite",
            Self::SetHistoryLimit(_) => "set_history_limit",
            Self::SetKeepRunningInBackground(_) => "set_keep_running_in_background",
            Self::SetLanguage(_) => "set_language",
            Self::SetLockScreenBlurMode(_) => "set_lock_screen_blur_mode",
            Self::SetLockScreenDisplayMode(_) => "set_lock_screen_display_mode",
            Self::SetLockScreenIntegrationEnabled(_) => "set_lock_screen_integration_enabled",
            Self::SetWallpaperSource(_) => "set_wallpaper_source",
            Self::SetStartAtLogin(_) => "set_start_at_login",
            Self::SetSyncInterval(_) => "set_sync_interval",
            Self::SetTheme(_) => "set_theme",
        }
    }
}
